# -*- coding: utf-8 -*-
"""Twitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vs9fI8InwQ9CLTJm7CHPaOUxY7si9aV1
"""

pip install dash

import requests
import dash
from dash import dcc, html
from dash.dependencies import Input, Output

# Fetching data from Twitter API
url = "https://twitter-api45.p.rapidapi.com/spaces.php"
headers = {
    "X-RapidAPI-Key": "f1025ce037msh2e7ac61c914e30fp143b0bjsnfc02bf62d970",
    "X-RapidAPI-Host": "twitter-api45.p.rapidapi.com"
}
params = {
    "id": "1yoJMwpbmaXKQ"
}

response = requests.get(url, headers=headers, params=params)
data = response.json()

# Creating Dash app
app = dash.Dash(__name__)

# Layout of the dashboard
app.layout = html.Div([
    html.H1("Twitter Spaces Dashboard"),
    html.H2("Space Details:"),
    html.Div([
        html.Div("Space ID: "),
        html.Div(data.get("id", "N/A")),
    ]),
    html.Div([
        html.Div("Space Host: "),
        html.Div(data.get("host", "N/A")),
    ]),
    html.Div([
        html.Div("Space Description: "),
        html.Div(data.get("description", "N/A")),
    ]),
])

if __name__ == '__main__':
    app.run_server(debug=True)

